#include<iostream>

using namespace std;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int fibonacci(int num) {
  if (num < 2) return 1;
  else return fibonacci(num - 1) + fibonacci(num - 2);
}

int main() {
  int sum = 0;

  int counter = 0; // while loop is redudant code after solving term
  while (fibonacci(counter) < 4000000) counter++;
  counter--; // (n+1)th term --> nth term

  for (size_t i = 0; i < counter; i++)
    if (fibonacci(i) % 2 == 0) sum += fibonacci(i);

  std::cout << sum << '\n';
  return 0;
}