"""

Problem 2 - Even Fibonacci Numbers (direct ver) [https://projecteuler.net/problem=2]

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci
sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

num, num_plus = 1, 2

total = 0
while num_plus <= 4_000_000:
    if num % 2 == 0:
        total += num
    # Re-sequencing for fibonacci
    num, num_plus = num_plus, num + num_plus

print(total)
